In [3]:
#Why to we want to use the a special library called numpy while the same task can be easily done by normal python code:
#The answer is very simple. SPEED. The numpy uses the precompiled c code as the backend.

In [4]:
#VECTORIZATION AND BROADCASTING

In [5]:
#ARRAY FUNDAMENTALS

In [6]:
import numpy as np

In [8]:
a = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]   
    ]
)

a.shape

(2, 3)

In [11]:
a[0][1] = 8 #Note that the numpy is 0-indexed.
print(a)

[[1 8 3]
 [4 5 6]]


In [13]:
b = np.array(
    [1, 2, 3, 4, 5, 6]
)

print(b[:3]) #We also assign this to the variable rather that printing.
print(b[2:])

[1 2 3]
[3 4 5 6]


In [14]:
#ARRAY ATTRIBUTES

In [21]:
c = np.array( #This is a two dimensional array
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [7, 8, 9, 12]
    ]
)

d = np.array( #This is a one dimensional array
    [1, 2]
)

e = np.array(34) #This is a zero dimensional array.

In [25]:
print(a.ndim) #Get the number of dimensions.
print(d.ndim)
print(e.ndim)

2
1
0


In [27]:
print(a.dtype)
print(d.dtype)

int64
int64


In [28]:
#CREATION OF COMMON BASIC ARRAYS

In [30]:
np.zeros(2)

array([0., 0.])

In [34]:
print(np.zeros((2, 3)))
print('SPLITTER')
print(np.zeros((2, 3, 5)))

[[0. 0. 0.]
 [0. 0. 0.]]
HELLO
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [38]:
print(np.ones(5))
print('SPLITTER')
print(np.ones((5, 5, 5)))

[1. 1. 1. 1. 1.]
SPLITTER
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [40]:
print(np.empty(3))#Empty arrays are not initialized with any values. It is usefull when we want to override all the values in the future.

[9.40528331e-312 0.00000000e+000 6.47591605e-319]


In [42]:
print(np.arange(2, 9, 2)) #start value, end value, step value

[2 4 6 8]


In [44]:
print(np.linspace(0, 10, num = 5)) #Start value, End value, No of elements. It automatically calculates the step value based upon the number of elements.

[ 0.   2.5  5.   7.5 10. ]


In [47]:
#We obeserve till now that all the elements are acutally floats but there is way to specify the datatype required.
x = np.ones( #Similarly this could be also done for zeros
    2, dtype = np.int64
)

print(x)

[1 1]


In [48]:
# SORTING AND CONCATENATE

In [50]:
arr = np.array(
    [2, 1, 2, 4, 56,7, 34, 99]
)

print(np.sort(arr))

[ 1  2  2  4  7 34 56 99]


In [52]:
arr = np.sort(
    [30, 10, 20]
)

print(np.argsort(arr)) #This actually returns the index after sorting.

[0 1 2]


In [58]:
x = np.array(
    [
        [1, 2],
        [3, 4]
    ]
)

y = np.array(
    [
        [5, 6],
        [7, 8]
    ]
)

print(np.concatenate((x, y), axis = 0))
print(np.concatenate((x, y), axis = 1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [60]:
# RESHAPE ARRAYS (IT GIVES NEW SHAPE TO THE ARRAY WITHOUT CHANGING THE DATA)

In [71]:
a = np.arange(6)
print(a)

print('SEPERATOR')

print(a.reshape(2, 3))

print('SEPERATOR')

print(np.reshape(a, (2, 3)))

[0 1 2 3 4 5]
SEPERATOR
[[0 1 2]
 [3 4 5]]
SEPERATOR
[[0 1 2]
 [3 4 5]]


In [74]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1.shape)
print(a1.ndim)

a2 = a[np.newaxis, : ]
print(a2.shape)
print(a2)

(5,)
1
(1, 5)
[[1 2 3 4 5]]


In [76]:
# INDEXING AND SLICING

In [78]:
arr = np.array(
    [12, 89, 45]
)

print(arr[1:])
print(arr[-2])
print(arr[-2: ])

[89 45]
89
[89 45]


In [83]:
arr = np.array( #This is a two dimensional array
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [7, 8, 9, 12]
    ]
)

print(arr < 6)
print('SEPERATOR')
print(arr[arr < 6])
print(arr[arr % 2 == 0])
print(arr[(arr < 6) & (arr % 2 == 0)])

[[ True  True  True  True]
 [ True False False False]
 [False False False False]]
SEPERATOR
[1 2 3 4 5]
[ 2  4  6  8  8 12]
[2 4]


In [85]:
print(np.nonzero((arr < 6) & (arr % 2 == 0))) #This returns the index rather that the element. Here the [0,1]=>2 and [0,3]=>4

(array([0, 0]), array([1, 3]))


In [86]:
# HORIZONDAL, VERTICAL STACK AND HORIZONTAL SPLIT

In [88]:
a1 = np.array(
    [
        [1, 2],
        [3, 4]
    ]
)

a2 = np.array(
    [
        [5, 6],
        [7, 8]
    ]
)

print(np.vstack((a1, a2)))
print('SEPERATOR')
print(np.hstack((a1, a2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
SEPERATOR
[[1 2 5 6]
 [3 4 7 8]]


In [94]:
arr1 = np.arange(1, 25).reshape(2, 12)
print(arr1)

arr2 = np.hsplit(arr1, 3)
print(arr2)

print('SEPERATOR')

arr2 = np.hsplit(arr1, (3,  4))
print(arr2)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
[array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]
SEPERATOR
[array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4],
       [16]]), array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [17, 18, 19, 20, 21, 22, 23, 24]])]


In [95]:
# VIEW AND COPY

In [100]:
arr1 = np.arange(6)
arr2 = arr1 #Technically we are actually creating the view.
arr3 = arr1.copy() #Technically we are actually creating the copy.
print(arr2)

arr2[2] = 10
arr3[1] = 20

print(arr1) #From this its very clear that the python actually creates the referenced copies. All the copies point to the same memeory location.


[0 1 2 3 4 5]
[ 0  1 10  3  4  5]


In [101]:
#ADDITION, SUBSTRACTION, MULTIPLICATION AND DIVISION OF ARRAYS

In [104]:
arr1 = np.arange(1, 5)
arr2 = np.arange(1, 5)
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[2 4 6 8]
[0 0 0 0]
[ 1  4  9 16]
[1. 1. 1. 1.]


In [110]:
arr3 = np.reshape(arr1, (2, 2))
print(arr3)

print(arr3.sum())
print(arr3.sum(axis = 0))
print(arr3.sum(axis = 1))

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


In [114]:
# MIN, MAX, MEAN, STD(standard deviation, PROD

In [116]:
print(arr3.max())
print(arr3.max(axis = 0))
print(arr3.max(axis = 1))
#Similary it applies for the MIN, MEAN, STD

4
[3 4]
[2 4]


In [117]:
# GENERATING RANDOM NUMBERS

In [119]:
#First see a bit older version:
print(np.random.randint(2, 9, (3, 2))) # Start, End, (Shape required)

[[2 3]
 [2 8]
 [3 4]]


In [120]:
#Newer version
rng = np.random.default_rng() # rng => Random Number Generator
print(rng.integers(2, 9, (3, 2)))

[[8 4]
 [5 7]
 [7 7]]


In [121]:
# UNIQUE ITEMS TRANSPOSING MATRIX REVERSE ARRAYS

In [122]:
print(arr3.transpose())

[[1 3]
 [2 4]]


In [123]:
#REVERSE OR FLIP ARRAYS